### PR TITLE
merge 1.4 as released in debian

### LINKED ISSUE #9: Obsolete references to git.debian.org
Alioth has been shut down, but there are still references to the Alioth repo in the source:

```console
$ git grep -F /git.debian.org/
debian/control:Homepage: http://git.debian.org/?p=collab-maint/tmperamental.git;a=summary
debian/control:Vcs-Git: git://git.debian.org/collab-maint/tmperamental.git
debian/control:Vcs-Browser: http://git.debian.org/?p=collab-maint/tmperamental.git
debian/copyright:Source: http://git.debian.org/?p=collab-maint/tmperamental.git;a=summary
```

Also, <http://git.debian.org/?p=collab-maint/tmperamental.git;a=summary> is set as homepage of this GitHub repo.

### PR DESCRIPTION
**Pull request by dkg**
This fixes a bunch of outstanding errors, makes tmperamental usable again (it was [failing](https://bugs.debian.org/941407)), and syncs up with debian.  It also closes #9 .

### CODE REVIEW

**Review by paultag — APPROVED** [review]

**Comment by paultag** [comment]
Thank you! Looks like there's a merge conflict though. Mind doing a merge with master?

**Comment by paultag** [comment]
Also @dkg do you want commit on this repo too? Thanks for all your work maintaining this!

**Comment by dkg** [comment]
I have no idea what that merge conflict is about, or why git is confused..  afaict, the only thing in your "master" branch that's not in the branch i've pushed to salsa (and to @dkg/tmperamental master here) is merge commits.

I've gone ahead and merged the other way (on my master, merging yours) and git had no trouble with it.

if you want to give me push access to this repo, i'd be happy to use it.

1.4 now has some effective autopkgtests as well, fwiw.

**Comment by paultag** [comment]
@dkg thank you! Also gave you commit here! Thank you for all your work on this package!

**Pull request merged**
